### ISSUE TITLE
Cookie Warning

### ISSUE THREAD

**Issue by thanhpd** [yasserg/crawler4j#102] opened 2015-12-03 06:01 UTC
Hello, while using your library for Wikipedia I got this warning:

> 12095 [Crawler 1] INFO edu.uci.ics.crawler4j.crawler.WebCrawler - URL: https://vi.wikipedia.org/wiki/C%C3%B4ng_ngh%E1%BB%87
> Dec 03, 2015 12:30:00 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
> WARNING: Invalid cookie header: "Set-Cookie: WMF-Last-Access=03-Dec-2015;Path=/;HttpOnly;Expires=Mon, 04 Jan 2016 00:00:00 GMT". Invalid 'expires' attribute: Mon, 04 Jan 2016 00:00:00 GMT

The pom.xml file has HttpClient as below:

```
 <dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.4</version>
    <scope>compile</scope>
</dependency>
```

As far as I'm aware, this is a bug of Apache HttpClient and can be fixed in a various ways. However, it is a bit difficult since the whole HttpClient process is handled by the library. Therefore I'm asking you to take a look at my issue and enlighten me. Thank you very much!

**Comment by rahulravindran0108** [comment] 2016-09-19 15:53
^ same issue

**Comment by SaeedMasoumi** [comment] 2017-01-27 08:02
The issue is still not resolved !

**Comment by s17t** [comment] 2017-03-09 11:40
Closed this in PR #191

**Closed by s17t** 2017-03-09 11:40 UTC
